# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a60ad555070969ce20638624a26716e3716f04ed4973130cceec40f8cee113889ddb5d0fd603b9b11c337d1ab69bd1e1d67011760a725e70dd5259b41fe689

test:
  secret_key_base: fdf70489c43f3b4465f2b563787e4bea3214ef75f5195fa42d7023e6d29e3a52c42243e81810ad831e76414b2a3078667c67fffb72d4f89f550edc6290512e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
